/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface JmLbmComp1 {
        "ambulanceId": string;
        "apiBase": string;
        "basePath": string;
    }
    interface LbmAmbulanceWlApp {
        "ambulanceId": string;
        "apiBase": string;
        "basePath": string;
    }
    interface LbmAmbulanceWlEditor {
        "ambulanceId": string;
        "apiBase": string;
        "entryId": string;
    }
    interface LbmAmbulanceWlList {
        "ambulanceId": string;
        "apiBase": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface RoomManager {
        "ambulanceId": string;
        "apiBase": string;
    }
    interface ScheduleManager {
        "ambulanceId": string;
        "apiBase": string;
    }
}
export interface LbmAmbulanceWlEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLbmAmbulanceWlEditorElement;
}
export interface LbmAmbulanceWlListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLbmAmbulanceWlListElement;
}
declare global {
    interface HTMLJmLbmComp1Element extends Components.JmLbmComp1, HTMLStencilElement {
    }
    var HTMLJmLbmComp1Element: {
        prototype: HTMLJmLbmComp1Element;
        new (): HTMLJmLbmComp1Element;
    };
    interface HTMLLbmAmbulanceWlAppElement extends Components.LbmAmbulanceWlApp, HTMLStencilElement {
    }
    var HTMLLbmAmbulanceWlAppElement: {
        prototype: HTMLLbmAmbulanceWlAppElement;
        new (): HTMLLbmAmbulanceWlAppElement;
    };
    interface HTMLLbmAmbulanceWlEditorElementEventMap {
        "editor-closed": string;
    }
    interface HTMLLbmAmbulanceWlEditorElement extends Components.LbmAmbulanceWlEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLLbmAmbulanceWlEditorElementEventMap>(type: K, listener: (this: HTMLLbmAmbulanceWlEditorElement, ev: LbmAmbulanceWlEditorCustomEvent<HTMLLbmAmbulanceWlEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLLbmAmbulanceWlEditorElementEventMap>(type: K, listener: (this: HTMLLbmAmbulanceWlEditorElement, ev: LbmAmbulanceWlEditorCustomEvent<HTMLLbmAmbulanceWlEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLLbmAmbulanceWlEditorElement: {
        prototype: HTMLLbmAmbulanceWlEditorElement;
        new (): HTMLLbmAmbulanceWlEditorElement;
    };
    interface HTMLLbmAmbulanceWlListElementEventMap {
        "entry-clicked": string;
    }
    interface HTMLLbmAmbulanceWlListElement extends Components.LbmAmbulanceWlList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLLbmAmbulanceWlListElementEventMap>(type: K, listener: (this: HTMLLbmAmbulanceWlListElement, ev: LbmAmbulanceWlListCustomEvent<HTMLLbmAmbulanceWlListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLLbmAmbulanceWlListElementEventMap>(type: K, listener: (this: HTMLLbmAmbulanceWlListElement, ev: LbmAmbulanceWlListCustomEvent<HTMLLbmAmbulanceWlListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLLbmAmbulanceWlListElement: {
        prototype: HTMLLbmAmbulanceWlListElement;
        new (): HTMLLbmAmbulanceWlListElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLRoomManagerElement extends Components.RoomManager, HTMLStencilElement {
    }
    var HTMLRoomManagerElement: {
        prototype: HTMLRoomManagerElement;
        new (): HTMLRoomManagerElement;
    };
    interface HTMLScheduleManagerElement extends Components.ScheduleManager, HTMLStencilElement {
    }
    var HTMLScheduleManagerElement: {
        prototype: HTMLScheduleManagerElement;
        new (): HTMLScheduleManagerElement;
    };
    interface HTMLElementTagNameMap {
        "jm-lbm-comp1": HTMLJmLbmComp1Element;
        "lbm-ambulance-wl-app": HTMLLbmAmbulanceWlAppElement;
        "lbm-ambulance-wl-editor": HTMLLbmAmbulanceWlEditorElement;
        "lbm-ambulance-wl-list": HTMLLbmAmbulanceWlListElement;
        "my-component": HTMLMyComponentElement;
        "room-manager": HTMLRoomManagerElement;
        "schedule-manager": HTMLScheduleManagerElement;
    }
}
declare namespace LocalJSX {
    interface JmLbmComp1 {
        "ambulanceId"?: string;
        "apiBase"?: string;
        "basePath"?: string;
    }
    interface LbmAmbulanceWlApp {
        "ambulanceId"?: string;
        "apiBase"?: string;
        "basePath"?: string;
    }
    interface LbmAmbulanceWlEditor {
        "ambulanceId"?: string;
        "apiBase"?: string;
        "entryId"?: string;
        "onEditor-closed"?: (event: LbmAmbulanceWlEditorCustomEvent<string>) => void;
    }
    interface LbmAmbulanceWlList {
        "ambulanceId"?: string;
        "apiBase"?: string;
        "onEntry-clicked"?: (event: LbmAmbulanceWlListCustomEvent<string>) => void;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface RoomManager {
        "ambulanceId"?: string;
        "apiBase"?: string;
    }
    interface ScheduleManager {
        "ambulanceId"?: string;
        "apiBase"?: string;
    }
    interface IntrinsicElements {
        "jm-lbm-comp1": JmLbmComp1;
        "lbm-ambulance-wl-app": LbmAmbulanceWlApp;
        "lbm-ambulance-wl-editor": LbmAmbulanceWlEditor;
        "lbm-ambulance-wl-list": LbmAmbulanceWlList;
        "my-component": MyComponent;
        "room-manager": RoomManager;
        "schedule-manager": ScheduleManager;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "jm-lbm-comp1": LocalJSX.JmLbmComp1 & JSXBase.HTMLAttributes<HTMLJmLbmComp1Element>;
            "lbm-ambulance-wl-app": LocalJSX.LbmAmbulanceWlApp & JSXBase.HTMLAttributes<HTMLLbmAmbulanceWlAppElement>;
            "lbm-ambulance-wl-editor": LocalJSX.LbmAmbulanceWlEditor & JSXBase.HTMLAttributes<HTMLLbmAmbulanceWlEditorElement>;
            "lbm-ambulance-wl-list": LocalJSX.LbmAmbulanceWlList & JSXBase.HTMLAttributes<HTMLLbmAmbulanceWlListElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "room-manager": LocalJSX.RoomManager & JSXBase.HTMLAttributes<HTMLRoomManagerElement>;
            "schedule-manager": LocalJSX.ScheduleManager & JSXBase.HTMLAttributes<HTMLScheduleManagerElement>;
        }
    }
}
